FROM node:20-alpine
RUN npm i -g pnpm
WORKDIR /app
COPY . .
ENV NEXT_PUBLIC_API_URL=https://api.dashboard.sistemautomacao.com
RUN pnpm --filter @dashboard/web install
RUN pnpm --filter @dashboard/web build
WORKDIR /app/apps/web
EXPOSE 3000
CMD ["pnpm","start"]
